package com.zooz.common.client.ecomm.utils;

import com.zooz.common.client.ecomm.beans.responses.PaymentDetailsResponse;

/**
 * Created by yigalpinhasi on 11/26/14.
 */
public class PaymentDetailsSignatureCalculator extends PaymentIPNSignatureCalculator{

    /**
     * The PaymentDetailsSignatureCalculator call is used to verify that the signature field of the IPN has come from Zooz.
     *
     * @param paymentDetailsResponse the PaymentDetailsResponse object generated by the SDK, not null.
     * @param merchantServerApiKey a key provided by Zooz to the merchant.
     */
     public PaymentDetailsSignatureCalculator(PaymentDetailsResponse paymentDetailsResponse, String merchantServerApiKey) {
        super(paymentDetailsResponse.getAmount(),
              paymentDetailsResponse.getPaymentId(),
              paymentDetailsResponse.getPaymentMethod() != null ? paymentDetailsResponse.getPaymentMethod().getPaymentMethodLastUsedTimestamp() : null,
              paymentDetailsResponse.getPaymentMethod() != null ? paymentDetailsResponse.getPaymentMethod().getPaymentMethodToken() : null,
              paymentDetailsResponse.getProcessorReferenceId(),
              merchantServerApiKey);
    }

}
